runtime: python311

env_variables:
  FRED_API_KEY: "f4a4524122986e76cfdb0e5b519756b6"
  TELEGRAM_BOT_TOKEN: "7904419848:AAHNuYen7BM8W66gIXmsEiW36toUyIs2cf4"
  TELEGRAM_CHAT_ID: "44705783"

handlers:
- url: /.*
  script: auto

automatic_scaling:
  min_instances: 0
  max_instances: 2
